<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-10-09T17:14:47 IST" name="Suite" finished-at="2024-10-09T17:15:01 IST" duration-ms="14017">
    <groups>
    </groups>
    <test started-at="2024-10-09T17:14:47 IST" name="Test" finished-at="2024-10-09T17:15:01 IST" duration-ms="14017">
      <class name="api.testcases.UserTestDD">
        <test-method signature="testDeleteUser(java.lang.String)[pri:2, instance:api.testcases.UserTestDD@8462f31]" started-at="2024-10-09T17:15:01 IST" name="testDeleteUser" data-provider="UserNameData" finished-at="2024-10-09T17:15:01 IST" duration-ms="0" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.NegativeArraySizeException: -1]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.NegativeArraySizeException: -1
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:58)
at org.testng.internal.invokers.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:159)
at org.testng.internal.Parameters.handleParameters(Parameters.java:809)
at org.testng.internal.Parameters.handleParameters(Parameters.java:734)
at org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:72)
at org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:51)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:946)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.NegativeArraySizeException: -1
at api.utilities.DataProviders.UserNameDataProvider(DataProviders.java:35)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:54)
... 25 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeleteUser -->
      </class> <!-- api.testcases.UserTestDD -->
      <class name="api.testcases.UserTest">
        <test-method is-config="true" signature="generateTestData()[pri:0, instance:api.testcases.UserTest@7d9d0818]" started-at="2024-10-09T17:14:48 IST" name="generateTestData" finished-at="2024-10-09T17:14:49 IST" duration-ms="534" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- generateTestData -->
        <test-method signature="testCreateUser()[pri:1, instance:api.testcases.UserTest@7d9d0818]" started-at="2024-10-09T17:14:49 IST" name="testCreateUser" finished-at="2024-10-09T17:14:55 IST" duration-ms="6506" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreateUser -->
        <test-method signature="testGetUserData()[pri:2, instance:api.testcases.UserTest@7d9d0818]" started-at="2024-10-09T17:14:55 IST" name="testGetUserData" finished-at="2024-10-09T17:14:57 IST" duration-ms="1359" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetUserData -->
        <test-method signature="testUpdateUser()[pri:3, instance:api.testcases.UserTest@7d9d0818]" started-at="2024-10-09T17:14:57 IST" name="testUpdateUser" finished-at="2024-10-09T17:14:59 IST" duration-ms="2947" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdateUser -->
        <test-method signature="testDeleteUser()[pri:4, instance:api.testcases.UserTest@7d9d0818]" started-at="2024-10-09T17:14:59 IST" name="testDeleteUser" finished-at="2024-10-09T17:15:01 IST" duration-ms="1703" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeleteUser -->
      </class> <!-- api.testcases.UserTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
